import { PlayIcon } from '@heroicons/react/solid';
import {
  Firebase,
  Icon,
  Nextdotjs,
  Stripe,
} from '@icons-pack/react-simple-icons';
import Head from 'next/head';
import { ReactNode, useState } from 'react';
import DocCard from './doc-card';

const ToolTab = ({ title, TabIcon }: { title: string; TabIcon: Icon }) => {
  return (
    <div className="col-span-2 px-4 justify-center flex items-center space-x-2 text-center">
      <TabIcon size={24} className="text-gray-500" />
      <span className="block text-gray-600">{title}</span>
    </div>
  );
};

type Pattern = {
  title: string;
  steps: string[];
  tools: string[];
};

type Props = {
  type: 'payments' | 'subscriptions' | 'connect';
  title: string;
  description: ReactNode;
  scenes: string[];
  patterns: Pattern[];
  videoURL: string;
};

const TutorialKit = ({
  title,
  description,
  patterns,
  scenes,
  type,
  videoURL,
}: Props) => {
  const [pattern, setPattern] = useState<Pattern>(patterns[0]);

  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div>
        <div className="bg-gray-50 shadow-sm">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="py-10 lg:flex items-center">
              <a
                href={videoURL}
                target="_blank"
                className="aspect-video bg-slate-800 flex items-center justify-center rounded-lg lg:w-96 lg:mr-10 mb-6 lg:mb-0 shadow-lg hover:shadow-xl transition-shadow"
                rel="noreferrer"
              >
                <PlayIcon className="w-20 h-20 text-gray-300 opacity-40" />
              </a>
              <div className="flex-1">
                <h1 className="text-2xl mb-4 leading-6 font-semibold text-gray-800">
                  {title}
                </h1>
                <div className="text-gray-500 mb-6">{description}</div>
                <div>
                  <h2 className="text-gray-700 font-bold mb-2">利用シーン</h2>
                  <p className="text-gray-500">{scenes.join(' / ')}</p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
          <div className="mb-20">
            <div className="grid grid-cols-7 gap-2 sticky top-0 py-4 border-b bg-white">
              <div></div>
              <ToolTab TabIcon={Stripe} title="Stripe" />
              <ToolTab TabIcon={Nextdotjs} title="Next.js" />
              <ToolTab TabIcon={Firebase} title="Firebase" />
            </div>
            <div className="divide-dashed divide-y">
              {pattern.steps.map((step, index) => (
                <div className="grid grid-cols-7 gap-2 py-6" key={index}>
                  <h2>
                    <span className="text-gray-500 font-bold">
                      STEP {index + 1}
                    </span>
                    <p className="font-bold text-gray-700 text-lg">{step}</p>
                  </h2>
                  {pattern.tools.map((tool) => (
                    <div key={tool} className="col-span-2">
                      <DocCard type={type} tool={tool} index={index + 1} />
                    </div>
                  ))}
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TutorialKit;
