import type { NextPage } from 'next';
import Head from 'next/head';
import TutorialKit from '../components/tutorial-kit';
import ExternalLink from '../components/external-link';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <TutorialKit
        videoURL="https://xxx"
        type="connect"
        title="マーケットプレイス"
        description={
          <p>
            メルカリのようなユーザー間の売買サービスは
            <ExternalLink href="https://stripe.com/jp/connect">
              Stripe Connect
            </ExternalLink>
            で実現できます。
          </p>
        }
        scenes={[
          'ショッピングサイト',
          '有料コンテンツの販売',
          'グッズ販売',
          'チケット販売',
          '有料機能のアンロック',
          '投げ銭',
        ]}
      />
    </div>
  );
};

export default Home;
