import { Tab } from '@headlessui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { classNames } from '../lib/class-names';
import styles from '../styles/Home.module.css';

const FLOW = [
  {
    title: '環境構築',
    stripe: 'xxx',
    react: 'xxx',
    nodejs: 'xxx',
  },
];

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid grid-cols-7 mb-20">
        <div className="border-b py-4"></div>
        <div className="col-span-2  py-4 border-b">Stripe</div>
        <div className="col-span-2  py-4 border-b">React</div>
        <div className="col-span-2  py-4 border-b">Node.js</div>
        {FLOW.map((item, index) => (
          <>
            <div className="py-10">
              <h2>STEP {index + 1}</h2>
              <p className="font-bold text-lg">{item.title}</p>
            </div>
            <div className="py-10 col-span-2">{item.stripe}</div>
            <div className="py-10 col-span-2">{item.react}</div>
            <div className="py-10 col-span-2">{item.nodejs}</div>
          </>
        ))}
        <div></div>
      </div>
    </div>
  );
};

export default Home;
