import type { NextPage } from 'next';
import Head from 'next/head';
import TutorialKit from '../components/tutorial-kit';
import ExternalLink from '../components/external-link';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TutorialKit
        type="payments"
        patterns={[
          {
            title: 'Firebase拡張機能',
            steps: [
              '環境構築',
              '商品の作成と表示',
              'フルフィルメントの実装',
              '商品の購入',
              '決済情報の管理',
            ],
            tools: ['stripe', 'nextjs', 'firebase'],
          },
        ]}
        title="商品の販売"
        description={
          <p>
            Amazonのようなショッピングサイトは
            <ExternalLink href="https://stripe.com/jp/payments">
              Stripe Payments
            </ExternalLink>
            で実現できます。
          </p>
        }
        scenes={[
          'ショッピングサイト',
          '有料コンテンツの販売',
          'グッズ販売',
          'チケット販売',
          '有料機能のアンロック',
          '投げ銭',
        ]}
      />
    </div>
  );
};

export default Home;
