import type { NextPage } from 'next';
import Head from 'next/head';
import TutorialKit from '../components/tutorial-kit';
import ExternalLink from '../components/external-link';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TutorialKit
        videoURL="https://xxx"
        type="subscriptions"
        patterns={[
          {
            title: 'Firebase拡張機能',
            steps: [
              '環境構築',
              '商品の作成と表示',
              'フルフィルメントの実装',
              '商品の購入',
              '決済情報の管理',
            ],
            tools: ['stripe', 'nextjs', 'firebase'],
          },
        ]}
        title="サブスクリプション"
        description={
          <p>
            Netflixのような継続支払いサービスは
            <ExternalLink href="https://stripe.com/jp/billing">
              Stripe Billing
            </ExternalLink>
            で実現できます。
          </p>
        }
        scenes={[
          'オンラインサロン',
          'eラーニング',
          'ファンクラブ',
          'メールマガジン購読',
          'SaaS',
          '有料機能のアンロック',
        ]}
      />
    </div>
  );
};

export default Home;
